// epk-writer.js — Build EAGPKG$$ v2.0 asset packs

import { writeU32BE, writeU64BE, concat, strBytes, crc32 } from './binary.js'

/**
 * Build an EPK blob from a list of { name, data } records.
 *
 * @param {string} epkName   e.g. "assets.epk"
 * @param {Array<{name: string, data: Uint8Array}>} files
 *   `name` should already be the in-pack path (no leading dir component),
 *   e.g. "assets/minecraft/textures/stone.png"
 * @returns {Uint8Array}
 */
export function buildEpk(epkName, files) {
  const enc = new TextEncoder()
  const VERSION = 'ver2.0'
  const COMMENT  = 'Generated by EPW Tools\n'

  // ── Header ─────────────────────────────────────────────────────────────────
  const magic   = strBytes('EAGPKG$$')
  const verPart = new Uint8Array([VERSION.length, ...enc.encode(VERSION)])
  const fnPart  = new Uint8Array([epkName.length, ...enc.encode(epkName)])
  const nullTerm = new Uint8Array([0x00])
  const comment  = strBytes(COMMENT)
  const marker   = new Uint8Array([0x0a, 0x0a, 0x00])  // \n\n\0

  // ── Binary section header ──────────────────────────────────────────────────
  const binHeader = new Uint8Array(12)  // 8 timestamp + 4 count
  writeU64BE(binHeader, 0, Date.now())
  writeU32BE(binHeader, 8, files.length)

  // ── FILE records ───────────────────────────────────────────────────────────
  const recordParts = []

  for (const { name, data } of files) {
    const nameBytes   = enc.encode(name)
    const content     = data instanceof Uint8Array ? data : new Uint8Array(data)
    const recordSize  = 4 + content.length  // CRC32 (4) + content
    const checksum    = crc32(content)

    // "FILE" + 1-byte name length + name + 4-byte record size + 4-byte CRC32 + content
    const rec = new Uint8Array(4 + 1 + nameBytes.length + 4 + 4 + content.length)
    let rp = 0
    rec.set(strBytes('FILE'), rp);                      rp += 4
    rec[rp++] = nameBytes.length
    rec.set(nameBytes, rp);                             rp += nameBytes.length
    writeU32BE(rec, rp, recordSize);                    rp += 4
    writeU32BE(rec, rp, checksum);                      rp += 4
    rec.set(content, rp)
    recordParts.push(rec)
  }

  const endMarker = strBytes('END$$')

  return concat(magic, verPart, fnPart, nullTerm, comment, marker,
                binHeader, ...recordParts, endMarker)
}
